//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHShopForntend.Resources.Components.Layout {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AGB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AGB() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHShopForntend.Resources.Components.Layout.AGB", typeof(AGB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Terms and Conditions (GTC) ähnelt.
        /// </summary>
        public static string Agb {
            get {
                return ResourceManager.GetString("Agb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 12 Collection and Delivery ähnelt.
        /// </summary>
        public static string CollectionDelivery {
            get {
                return ResourceManager.GetString("CollectionDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) Binding selection of the delivery option ähnelt.
        /// </summary>
        public static string CollectionDelivery1 {
            get {
                return ResourceManager.GetString("CollectionDelivery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If collection does not take place on time, we accept no liability for spoilage or loss of quality, especially in the case of perishable food products. ähnelt.
        /// </summary>
        public static string CollectionDelivery10 {
            get {
                return ResourceManager.GetString("CollectionDelivery10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) Delivery by our own delivery service ähnelt.
        /// </summary>
        public static string CollectionDelivery11 {
            get {
                return ResourceManager.GetString("CollectionDelivery11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;Delivery service is provided exclusively within the designated delivery areas.&lt;/li&gt;
        ///
        ///&lt;li&gt;Delivery typically occurs once a week or every two weeks, depending on the delivery area.&lt;/li&gt;
        ///
        ///&lt;li&gt;Customers will be informed of the exact delivery date.&lt;/li&gt;
        ///
        ///&lt;li&gt;The customer is obligated to accept the goods personally or through an authorized recipient on the agreed-upon date.&lt;/li&gt;
        ///
        ///&lt;li&gt;If delivery cannot be completed due to reasons attributable to the customer, the customer assumes responsibilit [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string CollectionDelivery12 {
            get {
                return ResourceManager.GetString("CollectionDelivery12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (4) Shipping via post / parcel service ähnelt.
        /// </summary>
        public static string CollectionDelivery13 {
            get {
                return ResourceManager.GetString("CollectionDelivery13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;Shipping is to the delivery address provided by the customer.&lt;/li&gt;
        ///
        ///&lt;li&gt;Delivery time depends on the information provided in the shop.&lt;/li&gt;
        ///
        ///&lt;li&gt;For perishable food items that require refrigeration during transport, shipping is at the customer&apos;s risk, especially if continuous refrigeration cannot be guaranteed.&lt;/li&gt;
        ///
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string CollectionDelivery14 {
            get {
                return ResourceManager.GetString("CollectionDelivery14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (5) Transfer of risk ähnelt.
        /// </summary>
        public static string CollectionDelivery15 {
            get {
                return ResourceManager.GetString("CollectionDelivery15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The risk of accidental loss or damage to the goods passes to the customer: ähnelt.
        /// </summary>
        public static string CollectionDelivery16 {
            get {
                return ResourceManager.GetString("CollectionDelivery16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;For in-store pickup: upon handover at the store&lt;/li&gt;
        ///
        ///&lt;li&gt;For delivery service: upon handover at the delivery address&lt;/li&gt;
        ///
        ///&lt;li&gt;For postal delivery: upon handover by the parcel service&lt;/li&gt;
        ///
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string CollectionDelivery17 {
            get {
                return ResourceManager.GetString("CollectionDelivery17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (6) Hygiene &amp; Freshness ähnelt.
        /// </summary>
        public static string CollectionDelivery18 {
            get {
                return ResourceManager.GetString("CollectionDelivery18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;Food products are carefully packaged and, if necessary, transported under refrigeration.&lt;/li&gt;
        ///
        ///&lt;li&gt;Customers are required to store the food products properly and check their quality immediately upon receipt.&lt;/li&gt;
        ///
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string CollectionDelivery19 {
            get {
                return ResourceManager.GetString("CollectionDelivery19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When placing an order, the customer selects one of the following options: ähnelt.
        /// </summary>
        public static string CollectionDelivery2 {
            get {
                return ResourceManager.GetString("CollectionDelivery2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collection in the store ähnelt.
        /// </summary>
        public static string CollectionDelivery3 {
            get {
                return ResourceManager.GetString("CollectionDelivery3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery by our own delivery service ähnelt.
        /// </summary>
        public static string CollectionDelivery4 {
            get {
                return ResourceManager.GetString("CollectionDelivery4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shipping via postal service / parcel service ähnelt.
        /// </summary>
        public static string CollectionDelivery5 {
            get {
                return ResourceManager.GetString("CollectionDelivery5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected option is binding once the order has been completed. Changes after order completion are only possible after consultation with us. ähnelt.
        /// </summary>
        public static string CollectionDelivery6 {
            get {
                return ResourceManager.GetString("CollectionDelivery6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) In-store pickup ähnelt.
        /// </summary>
        public static string CollectionDelivery7 {
            get {
                return ResourceManager.GetString("CollectionDelivery7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The customer can pick up the order in the store. ähnelt.
        /// </summary>
        public static string CollectionDelivery8 {
            get {
                return ResourceManager.GetString("CollectionDelivery8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The collection should take place within the specified time period. ähnelt.
        /// </summary>
        public static string CollectionDelivery9 {
            get {
                return ResourceManager.GetString("CollectionDelivery9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 2 Conclusion of Contract ähnelt.
        /// </summary>
        public static string ConclusionContract {
            get {
                return ResourceManager.GetString("ConclusionContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) The presentation of the products in the online shop does not constitute a legally binding offer, but rather a non-binding invitation to place an order. ähnelt.
        /// </summary>
        public static string ConclusionContract1 {
            get {
                return ResourceManager.GetString("ConclusionContract1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) By clicking the “Buy” / “Order now” button, the customer submits a binding offer to conclude a purchase agreement. ähnelt.
        /// </summary>
        public static string ConclusionContract2 {
            get {
                return ResourceManager.GetString("ConclusionContract2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) The purchase contract is concluded as soon as we accept the order by sending an order confirmation email or dispatch the goods. ähnelt.
        /// </summary>
        public static string ConclusionContract3 {
            get {
                return ResourceManager.GetString("ConclusionContract3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 4 Delivery and Shipping ähnelt.
        /// </summary>
        public static string DeliveryShipping {
            get {
                return ResourceManager.GetString("DeliveryShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) Delivery will be made to the delivery address specified by the customer within Germany. ähnelt.
        /// </summary>
        public static string DeliveryShipping1 {
            get {
                return ResourceManager.GetString("DeliveryShipping1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Delivery times are indicated in the online shop and begin after receipt of payment. ähnelt.
        /// </summary>
        public static string DeliveryShipping2 {
            get {
                return ResourceManager.GetString("DeliveryShipping2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) In the case of food products, the customer is obliged to accept the goods immediately at the agreed delivery time. ähnelt.
        /// </summary>
        public static string DeliveryShipping3 {
            get {
                return ResourceManager.GetString("DeliveryShipping3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (4) If acceptance is not made or is delayed for reasons attributable to the customer, we shall not be liable for any loss of quality, in particular in the case of perishable goods. ähnelt.
        /// </summary>
        public static string DeliveryShipping4 {
            get {
                return ResourceManager.GetString("DeliveryShipping4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 11 Final Provisions ähnelt.
        /// </summary>
        public static string FinalProvisions {
            get {
                return ResourceManager.GetString("FinalProvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) The law of the Federal Republic of Germany shall apply, excluding the UN Convention on Contracts for the International Sale of Goods. ähnelt.
        /// </summary>
        public static string FinalProvisions1 {
            get {
                return ResourceManager.GetString("FinalProvisions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Should any provision of these Terms and Conditions be invalid, the validity of the remaining provisions shall remain unaffected. ähnelt.
        /// </summary>
        public static string FinalProvisions2 {
            get {
                return ResourceManager.GetString("FinalProvisions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Any further liability is excluded. ähnelt.
        /// </summary>
        public static string Liabilit2 {
            get {
                return ResourceManager.GetString("Liabilit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 9 Liability ähnelt.
        /// </summary>
        public static string Liability {
            get {
                return ResourceManager.GetString("Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) In cases of slight negligence, we shall only be liable for breaches of essential contractual obligations (cardinal obligations) and limited to foreseeable damages. ähnelt.
        /// </summary>
        public static string Liability1 {
            get {
                return ResourceManager.GetString("Liability1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 3 Prices and Payment Terms ähnelt.
        /// </summary>
        public static string PricesPayment {
            get {
                return ResourceManager.GetString("PricesPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) All prices are final prices and include statutory VAT. ähnelt.
        /// </summary>
        public static string PricesPayment1 {
            get {
                return ResourceManager.GetString("PricesPayment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Any additional shipping costs will be displayed separately to the customer during the ordering process. ähnelt.
        /// </summary>
        public static string PricesPayment2 {
            get {
                return ResourceManager.GetString("PricesPayment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) Payment is made using the payment methods offered in the online shop ähnelt.
        /// </summary>
        public static string PricesPayment3 {
            get {
                return ResourceManager.GetString("PricesPayment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (4) The purchase price is due immediately upon conclusion of the contract. ähnelt.
        /// </summary>
        public static string PricesPayment4 {
            get {
                return ResourceManager.GetString("PricesPayment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 6 Retention of Title ähnelt.
        /// </summary>
        public static string RetentionTitle {
            get {
                return ResourceManager.GetString("RetentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The goods remain our property until full payment is received. ähnelt.
        /// </summary>
        public static string RetentionTitle1 {
            get {
                return ResourceManager.GetString("RetentionTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 7 Right of withdrawal ähnelt.
        /// </summary>
        public static string RightWithdrawal {
            get {
                return ResourceManager.GetString("RightWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) Consumers generally have a statutory right of withdrawal. ähnelt.
        /// </summary>
        public static string RightWithdrawal1 {
            get {
                return ResourceManager.GetString("RightWithdrawal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) However, the right of withdrawal is excluded pursuant to Section 312g Paragraph 2 No. 2 of the German Civil Code (BGB) for contracts for the supply of: ähnelt.
        /// </summary>
        public static string RightWithdrawal2 {
            get {
                return ResourceManager.GetString("RightWithdrawal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foods that can spoil quickly or ähnelt.
        /// </summary>
        public static string RightWithdrawal3 {
            get {
                return ResourceManager.GetString("RightWithdrawal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foodstuffs whose expiration date would be quickly exceeded, ähnelt.
        /// </summary>
        public static string RightWithdrawal4 {
            get {
                return ResourceManager.GetString("RightWithdrawal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sealed food products that are not suitable for return for reasons of health protection or hygiene if the seal has been removed after delivery. ähnelt.
        /// </summary>
        public static string RightWithdrawal5 {
            get {
                return ResourceManager.GetString("RightWithdrawal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) Details can be found in our cancellation policy, which is available in the online shop. ähnelt.
        /// </summary>
        public static string RightWithdrawal6 {
            get {
                return ResourceManager.GetString("RightWithdrawal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 1 Scope ähnelt.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) These General Terms and Conditions (GTC) apply to all contracts for the delivery of goods to the delivery address specified by the customer, which are concluded between ähnelt.
        /// </summary>
        public static string Scope1 {
            get {
                return ResourceManager.GetString("Scope1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and are concluded with consumers within the meaning of Section 13 of the German Civil Code (BGB). ähnelt.
        /// </summary>
        public static string Scope2 {
            get {
                return ResourceManager.GetString("Scope2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) A consumer is any natural person who enters into a legal transaction for purposes that are predominantly neither attributable to their commercial nor their independent professional activity. ähnelt.
        /// </summary>
        public static string Scope3 {
            get {
                return ResourceManager.GetString("Scope3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) Any differing terms and conditions of the customer shall not apply unless we expressly agree to their validity. ähnelt.
        /// </summary>
        public static string Scope4 {
            get {
                return ResourceManager.GetString("Scope4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 5 Special features of foodstuffs ähnelt.
        /// </summary>
        public static string SpecialFeaturesFoodstuffs {
            get {
                return ResourceManager.GetString("SpecialFeaturesFoodstuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) Our goods are food products and are subject to special hygiene and health requirements. ähnelt.
        /// </summary>
        public static string SpecialFeaturesFoodstuffs1 {
            get {
                return ResourceManager.GetString("SpecialFeaturesFoodstuffs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) The customer is obliged to inspect the delivered food products immediately upon receipt and to store them properly. ähnelt.
        /// </summary>
        public static string SpecialFeaturesFoodstuffs2 {
            get {
                return ResourceManager.GetString("SpecialFeaturesFoodstuffs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) The best before date (BBE) shown on the packaging does not constitute a guarantee date. ähnelt.
        /// </summary>
        public static string SpecialFeaturesFoodstuffs3 {
            get {
                return ResourceManager.GetString("SpecialFeaturesFoodstuffs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (4) Returns of opened, damaged or improperly stored food products are excluded. ähnelt.
        /// </summary>
        public static string SpecialFeaturesFoodstuffs4 {
            get {
                return ResourceManager.GetString("SpecialFeaturesFoodstuffs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 10 Transport damage ähnelt.
        /// </summary>
        public static string TransportDamage {
            get {
                return ResourceManager.GetString("TransportDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) The customer must immediately report any obvious transport damage to the delivery person and inform us. ähnelt.
        /// </summary>
        public static string TransportDamage1 {
            get {
                return ResourceManager.GetString("TransportDamage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) The statutory warranty rights remain unaffected. ähnelt.
        /// </summary>
        public static string TransportDamage2 {
            get {
                return ResourceManager.GetString("TransportDamage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die § 8 Warranty ähnelt.
        /// </summary>
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) The statutory warranty rights apply. ähnelt.
        /// </summary>
        public static string Warranty1 {
            get {
                return ResourceManager.GetString("Warranty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Defects resulting from improper storage, delayed acceptance or incorrect handling by the customer do not give rise to any warranty claims. ähnelt.
        /// </summary>
        public static string Warranty2 {
            get {
                return ResourceManager.GetString("Warranty2", resourceCulture);
            }
        }
    }
}
