//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHShopForntend.Resources.Components.Layout {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHShopForntend.Resources.Components.Layout.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bakery Products ähnelt.
        /// </summary>
        public static string DescriptionCardButton {
            get {
                return ResourceManager.GetString("DescriptionCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To butcher shop ähnelt.
        /// </summary>
        public static string DescriptionCardButton1 {
            get {
                return ResourceManager.GetString("DescriptionCardButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Delivery Schedule ähnelt.
        /// </summary>
        public static string DescriptionCardButton2 {
            get {
                return ResourceManager.GetString("DescriptionCardButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to Shop ähnelt.
        /// </summary>
        public static string DescriptionCardButton3 {
            get {
                return ResourceManager.GetString("DescriptionCardButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To select ähnelt.
        /// </summary>
        public static string DescriptionCardButton4 {
            get {
                return ResourceManager.GetString("DescriptionCardButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discover Now ähnelt.
        /// </summary>
        public static string DescriptionCardButton5 {
            get {
                return ResourceManager.GetString("DescriptionCardButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discover Our Range ähnelt.
        /// </summary>
        public static string DescriptionCardButton6 {
            get {
                return ResourceManager.GetString("DescriptionCardButton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To the Sweets ähnelt.
        /// </summary>
        public static string DescriptionCardButton7 {
            get {
                return ResourceManager.GetString("DescriptionCardButton7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoy the authentic taste of traditional flatbread—baked fresh for you every day. For the health-conscious, we also offer our healthy, fiber-rich whole-grain flatbread. ähnelt.
        /// </summary>
        public static string DescriptionCardText {
            get {
                return ResourceManager.GetString("DescriptionCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top quality for your enjoyment:&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Fresh lamb&lt;/li&gt;
        ///&lt;li&gt;Fresh veal and beef&lt;/li&gt;
        ///&lt;li&gt;Fresh chicken&lt;/li&gt;
        ///&lt;li&gt;Poultry and lamb liver&lt;/li&gt;
        ///&lt;li&gt;100% Halal, fresh daily and prepared according to the highest hygiene standards.&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText1 {
            get {
                return ResourceManager.GetString("DescriptionCardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We come to you! Take advantage of our regular delivery service. &lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Punctual delivery on fixed days every week.&lt;/li&gt;
        ///&lt;li&gt;We deliver our products—including fresh meat and all your daily essentials—directly to your doorstep.&lt;/li&gt;
        ///&lt;li&gt;Reliable, convenient, and always fresh—your groceries from Syriana, delivered right to you.&lt;/li&gt;
        ///&lt;li&gt;Find out the exact delivery times for your region.&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText2 {
            get {
                return ResourceManager.GetString("DescriptionCardText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From local specialties to European market favorites – we have it all.
        ///&lt;ul&gt;
        ///&lt;li&gt;Over 500 carefully selected items for your daily needs.&lt;/li&gt;
        ///&lt;li&gt;Top quality and attractive offers, all in one place.&lt;/li&gt;
        ///&lt;li&gt;Discover our product range now and enjoy a unique shopping experience.&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText3 {
            get {
                return ResourceManager.GetString("DescriptionCardText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pure Refreshment for Every Taste!
        ///&lt;ul&gt;
        ///&lt;li&gt;Experience pure refreshment with our Arabic beverages.&lt;/li&gt;
        ///&lt;li&gt;A wide selection of soft drinks and natural juices.&lt;/li&gt;
        ///&lt;li&gt;Enjoy our chilled drinks.&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText4 {
            get {
                return ResourceManager.GetString("DescriptionCardText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoy premium frozen products with a fresh taste and minimal effort.
        ///&lt;ul&gt;
        ///&lt;li&gt;Garden-fresh vegetables that retain their vitamins&lt;/li&gt;
        ///&lt;li&gt;Traditional specialties such as Kibbeh, Sambusa, and Falafel&lt;/li&gt;
        ///&lt;li&gt;Find everything you need for a delicious meal in record time&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText5 {
            get {
                return ResourceManager.GetString("DescriptionCardText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The perfect snack treat for your cozy evenings!
        ///&lt;ul&gt;
        ///&lt;li&gt;Freshly roasted seeds and nuts (sunflower seeds, pumpkin seeds, Chinese mix, nuts, and much more)&lt;/li&gt;
        ///&lt;li&gt;A wide variety of corn snacks in various flavors&lt;/li&gt;
        ///&lt;li&gt;Enjoy the finest selection of traditional Oriental snacks—available directly from us&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText6 {
            get {
                return ResourceManager.GetString("DescriptionCardText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whether as an elegant gift or for your own coffee table—our sweets are always a delight. Discover the world of fine Oriental confectionery.
        ///&lt;ul&gt;
        ///&lt;li&gt;Maamoul, Barazek, Ghraybeh, and much more await you.&lt;/li&gt;
        ///&lt;li&gt;Traditional recipes featuring high-quality ingredients for the ultimate indulgence.&lt;/li&gt;
        ///&lt;li&gt;Whether as an elegant gift or for your own coffee table—our sweets are always a highlight.&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DescriptionCardText7 {
            get {
                return ResourceManager.GetString("DescriptionCardText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fresh Arabic flatbreads daily ähnelt.
        /// </summary>
        public static string DescriptionCardTitle {
            get {
                return ResourceManager.GetString("DescriptionCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fresh Halal-Meat ähnelt.
        /// </summary>
        public static string DescriptionCardTitle1 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reliable and regular delivery service ähnelt.
        /// </summary>
        public static string DescriptionCardTitle2 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Our Product Range ähnelt.
        /// </summary>
        public static string DescriptionCardTitle3 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoy Arabic drinks. ähnelt.
        /// </summary>
        public static string DescriptionCardTitle4 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fresh Frozen Foods for Quick Meals ähnelt.
        /// </summary>
        public static string DescriptionCardTitle5 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arabian Roasted Goods &amp; Snacks ähnelt.
        /// </summary>
        public static string DescriptionCardTitle6 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exquisite Arabic Sweets ähnelt.
        /// </summary>
        public static string DescriptionCardTitle7 {
            get {
                return ResourceManager.GetString("DescriptionCardTitle7", resourceCulture);
            }
        }
    }
}
