//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHShopForntend.Resources.Components.Layout {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurDeliveryService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurDeliveryService() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHShopForntend.Resources.Components.Layout.OurDeliveryService", typeof(OurDeliveryService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address: ähnelt.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery areas &amp; fixed days ähnelt.
        /// </summary>
        public static string AreasFixed {
            get {
                return ResourceManager.GetString("AreasFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deliveries will be made: ähnelt.
        /// </summary>
        public static string AreasFixed1 {
            get {
                return ResourceManager.GetString("AreasFixed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;&lt;strong&gt;In Leutkirch&lt;/strong&gt; Daily: Leutkirch im Allgäu area and surrounding area&lt;/strong&gt; – Delivery day: Daily (only during our opening hours)&lt;/em&gt;&lt;/li&gt;
        ///
        ///&lt;li&gt;&lt;strong&gt;Towards Ravensburg&lt;/strong&gt; Once a week: Kisslegg, Wolfegg, Vogt, Waldburg, Schlier, Ravensburg, Weingarten, Baienfurt, Weißenau, Meckenbeuren, Tettnang, Bodnegg, Grünkraut, Amtzell and surrounding area&lt;/strong&gt; – Delivery day: Saturdays&lt;/li&gt;
        ///
        ///&lt;li&gt;&lt;strong&gt;Towards Lindau&lt;/strong&gt; Every two weeks: Lindau, Lindenberg im Allgäu,  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string AreasFixed2 {
            get {
                return ResourceManager.GetString("AreasFixed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is how the delivery service works ähnelt.
        /// </summary>
        public static string deliveryServiceWorks {
            get {
                return ResourceManager.GetString("deliveryServiceWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ol&gt;
        ///
        ///&lt;li&gt;Select the &quot;Delivery via our delivery service&quot; option when completing your purchase.&lt;/li&gt;
        ///
        ///&lt;li&gt;We will automatically notify you of the specific delivery date based on your delivery area.&lt;/li&gt;
        ///
        ///&lt;li&gt;Please collect your order in person or authorize an authorized person to collect it.&lt;/li&gt;
        ///
        ///&lt;li&gt;Food will be carefully packaged and refrigerated during transit if necessary.&lt;/li&gt;
        ///&lt;ol&gt; ähnelt.
        /// </summary>
        public static string deliveryServiceWorks1 {
            get {
                return ResourceManager.GetString("deliveryServiceWorks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail: ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact us if you have any questions ähnelt.
        /// </summary>
        public static string IfQuestions {
            get {
                return ResourceManager.GetString("IfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you have any questions about your delivery date or delivery area, please contact us: ähnelt.
        /// </summary>
        public static string IfQuestions1 {
            get {
                return ResourceManager.GetString("IfQuestions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Important instructions ähnelt.
        /// </summary>
        public static string ImportantInstructions {
            get {
                return ResourceManager.GetString("ImportantInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;
        ///
        ///&lt;li&gt;The delivery option is binding once the order has been completed.&lt;/li&gt;
        ///
        ///&lt;li&gt;For perishable food items, the customer is obligated to store the goods properly **immediately after delivery**.&lt;/li&gt;
        ///
        ///&lt;li&gt;Delivery dates may be postponed for unforeseen reasons. The customer will be informed in a timely manner.&lt;/li&gt;
        ///
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string ImportantInstructions1 {
            get {
                return ResourceManager.GetString("ImportantInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Our delivery service information ähnelt.
        /// </summary>
        public static string OurDeliveryServiceInformation {
            get {
                return ResourceManager.GetString("OurDeliveryServiceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Our delivery service delivers your orders regularly on fixed days, depending on the delivery area. ähnelt.
        /// </summary>
        public static string OurDeliveryServiceInformation1 {
            get {
                return ResourceManager.GetString("OurDeliveryServiceInformation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WhatsApp: ähnelt.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
    }
}
