//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHShopForntend.Resources.Components.Layout {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RightOfWithdrawal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RightOfWithdrawal() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHShopForntend.Resources.Components.Layout.RightOfWithdrawal", typeof(RightOfWithdrawal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Consequences of the revocation ähnelt.
        /// </summary>
        public static string ConsequencesRevocation {
            get {
                return ResourceManager.GetString("ConsequencesRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you cancel this contract, we will reimburse all payments received from you, including delivery costs for standard delivery, without undue delay and at the latest within 14 days from the day we receive your cancellation notice. This excludes any additional costs incurred due to a delivery method other than the cheapest standard delivery option. ähnelt.
        /// </summary>
        public static string ConsequencesRevocation1 {
            get {
                return ResourceManager.GetString("ConsequencesRevocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The refund will be issued using the same payment method you used for the original order, unless otherwise agreed. ähnelt.
        /// </summary>
        public static string ConsequencesRevocation2 {
            get {
                return ResourceManager.GetString("ConsequencesRevocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return of goods ähnelt.
        /// </summary>
        public static string ReturnGoods {
            get {
                return ResourceManager.GetString("ReturnGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you cancel the contract, please return the goods to us immediately and no later than 14 days after receipt. The customer bears the return shipping costs, to the extent permitted by law. ähnelt.
        /// </summary>
        public static string ReturnGoods1 {
            get {
                return ResourceManager.GetString("ReturnGoods1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RightOfWithdrawal ähnelt.
        /// </summary>
        public static string RightOfWithdrawall {
            get {
                return ResourceManager.GetString("RightOfWithdrawall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To exercise your right of withdrawal, you must inform us ähnelt.
        /// </summary>
        public static string RightOfWithdrawalText {
            get {
                return ResourceManager.GetString("RightOfWithdrawalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inform us of your decision to cancel the order by means of a clear statement (e.g. by email, Whatsapp or letter). ähnelt.
        /// </summary>
        public static string RightOfWithdrawalText1 {
            get {
                return ResourceManager.GetString("RightOfWithdrawalText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your legal rights as a consumer ähnelt.
        /// </summary>
        public static string RightsConsumer {
            get {
                return ResourceManager.GetString("RightsConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Consumers have the right to withdraw from an online order within fourteen (14) days without giving any reason, unless there is a legal exclusion. ähnelt.
        /// </summary>
        public static string RightsConsumer1 {
            get {
                return ResourceManager.GetString("RightsConsumer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cancellation period is 14 days from the day on which you or a third party named by you, who is not the carrier, have taken possession of the ordered goods. ähnelt.
        /// </summary>
        public static string RightsConsumer2 {
            get {
                return ResourceManager.GetString("RightsConsumer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special instructions for food ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1- Sealed food products: ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood1 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The right of withdrawal does not apply to food products that were delivered sealed if the seal has been broken after delivery. This is because these products are unsuitable for return for reasons of health protection or hygiene (§ 312g para. 2 no. 3 BGB). ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood2 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Perishable foods: ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood3 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is also no right of withdrawal for food products that spoil quickly or whose best-before date would soon be exceeded. ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood4 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Returns: ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood5 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Returns of opened food products will not be refunded. In exceptional cases. ähnelt.
        /// </summary>
        public static string SpecialInstructionsFood6 {
            get {
                return ResourceManager.GetString("SpecialInstructionsFood6", resourceCulture);
            }
        }
    }
}
