//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHShopForntend.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyPolicy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicy() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAHShopForntend.Resources.PrivacyPolicy", typeof(PrivacyPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7. Contact us ähnelt.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you have any questions about this privacy policy or the processing of your data, you can contact us by email: &lt;strong&gt;Syriana.lebensmittel@gmail.com&lt;/strong&gt; ähnelt.
        /// </summary>
        public static string ContactUsDescription {
            get {
                return ResourceManager.GetString("ContactUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6. Cookies ähnelt.
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We use cookies to save sessions and language preferences. These cookies are necessary for the website to function properly. You can set your browser to refuse cookies, but this may limit some features. ähnelt.
        /// </summary>
        public static string CookiesDescription {
            get {
                return ResourceManager.GetString("CookiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. What data we collect ähnelt.
        /// </summary>
        public static string DataCollection {
            get {
                return ResourceManager.GetString("DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login information (such as username and password). ähnelt.
        /// </summary>
        public static string DataCollectionDescription1 {
            get {
                return ResourceManager.GetString("DataCollectionDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cookies to save your login session and language preference. ähnelt.
        /// </summary>
        public static string DataCollectionDescription2 {
            get {
                return ResourceManager.GetString("DataCollectionDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General information provided by your browser (e.g. language or device type). ähnelt.
        /// </summary>
        public static string DataCollectionDescription3 {
            get {
                return ResourceManager.GetString("DataCollectionDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5. Data security ähnelt.
        /// </summary>
        public static string DataSecurity {
            get {
                return ResourceManager.GetString("DataSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We take appropriate technical and organizational measures to protect your data from unauthorized access, loss, or alteration. ähnelt.
        /// </summary>
        public static string DataSecurityDescription1 {
            get {
                return ResourceManager.GetString("DataSecurityDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last update: ähnelt.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string PrivacyPolicy1 {
            get {
                return ResourceManager.GetString("PrivacyPolicy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We respect your privacy and are committed to protecting your personal information. ähnelt.
        /// </summary>
        public static string PrivacyPolicyDescription {
            get {
                return ResourceManager.GetString("PrivacyPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Sharing of data ähnelt.
        /// </summary>
        public static string ShareData {
            get {
                return ResourceManager.GetString("ShareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We do not share your personal information with third parties, except when required by law or necessary to provide essential services (e.g., logging in or processing payments). ähnelt.
        /// </summary>
        public static string ShareDataDescription {
            get {
                return ResourceManager.GetString("ShareDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. How we use the data ähnelt.
        /// </summary>
        public static string UseData {
            get {
                return ResourceManager.GetString("UseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To provide a secure and personalized user experience. ähnelt.
        /// </summary>
        public static string UseDataDescription1 {
            get {
                return ResourceManager.GetString("UseDataDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To save your settings such as preferred language. ähnelt.
        /// </summary>
        public static string UseDataDescription2 {
            get {
                return ResourceManager.GetString("UseDataDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To improve the performance of our website and services. ähnelt.
        /// </summary>
        public static string UseDataDescription3 {
            get {
                return ResourceManager.GetString("UseDataDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4. Your rights ähnelt.
        /// </summary>
        public static string YourRights {
            get {
                return ResourceManager.GetString("YourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access your personal data or request a copy. ähnelt.
        /// </summary>
        public static string YourRightsDescription1 {
            get {
                return ResourceManager.GetString("YourRightsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request correction or deletion of your data. ähnelt.
        /// </summary>
        public static string YourRightsDescription2 {
            get {
                return ResourceManager.GetString("YourRightsDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object to certain processing methods. ähnelt.
        /// </summary>
        public static string YourRightsDescription3 {
            get {
                return ResourceManager.GetString("YourRightsDescription3", resourceCulture);
            }
        }
    }
}
